/*
 * mavi-audio.hpp
 * --------------
 *
 * ...
 */

#ifndef MAVI_AUDIO_HPP
#define MAVI_AUDIO_HPP

typedef const char* MaviAudioID;

extern const MaviAudioID
	MAVI_AUDIO_BTN_CALIB,
	MAVI_AUDIO_BTN_POWER,
	MAVI_AUDIO_BTN_SLEEP,
	MAVI_AUDIO_CALIB_FAILED,
	MAVI_AUDIO_CALIB_STARTED,
	MAVI_AUDIO_CALIB_SUCCESS,
	MAVI_AUDIO_IM_HAZARD,
	MAVI_AUDIO_STAIRS_ASC,
	MAVI_AUDIO_STAIRS_DESC,
	MAVI_AUDIO_STEP_FINAL,
	MAVI_AUDIO_STEP_FIRSTDOWN,
	MAVI_AUDIO_STEP_FIRSTUP,
	MAVI_AUDIO_STEP_SINGLEDOWN,
	MAVI_AUDIO_STEP_SINGLEUP,
	MAVI_AUDIO_SYSTEM_ON,
	MAVI_AUDIO_SYSTEM_PAUSED,
	MAVI_AUDIO_SYSTEM_READY,
	MAVI_AUDIO_SYSTEM_SHUTDOWN,
	MAVI_AUDIO_VIBRATE_CENTER,
	MAVI_AUDIO_VIBRATE_LEFT,
	MAVI_AUDIO_VIBRATE_RIGHT,
	MAVI_AUDIO_VIBRATE_LR,
	MAVI_AUDIO_VIBRATE_CL,
	MAVI_AUDIO_VIBRATE_CR,
	MAVI_AUDIO_VIBRATE_ALL,
	MAVI_AUDIO_WARNING_BATTERYLOW,
	MAVI_AUDIO_WARNING_BATTERYCRITICAL,
	MAVI_AUDIO_WARNING_NONOPERATIONAL,
	MAVI_AUDIO_WARNING_SENSORFAILURE;

void maviAudioPlay(MaviAudioID audioFile);

#endif
